name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  your-job-name:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Use OpenAI API Key
      env:
        API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo $OPENAI_API_KEY
        # You can use $OPENAI_API_KEY in your code
